version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: eventease-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: eventease-mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  backend:
    build: ./backend
    container_name: eventease-backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/eventease
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventease-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  mongo-data:
